---
.travis.yml:
  env_matrix:
  - PUPPET_GEM_VERSION="~> 2.7.0"
  - PUPPET_GEM_VERSION="~> 3.0.0"
  - PUPPET_GEM_VERSION="~> 3.1.0"
  - PUPPET_GEM_VERSION="~> 3.2.0"
  - PUPPET_GEM_VERSION="~> 3.4.0"
  excludes:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 2.7.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 2.7.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.1.0"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.2.0"
Gemfile:
  unmanaged: true
Rakefile:
  unmanaged: true
spec/spec_helper.rb:
  unmanaged: true
spec/acceptance/nodesets/centos-59-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/centos-64-x64-pe.yml:
  unmanaged: true
spec/acceptance/nodesets/centos-65-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/ubuntu-server-10044-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/ubuntu-server-12042-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/ubuntu-server-1404-x64.yml:
  unmanaged: true
