---
.travis.yml:
  script: "\"bundle exec rake spec SPEC_OPTS='--format documentation'\""
Gemfile:
  unmanaged: true
Rakefile:
  unmanaged: true
spec/spec_helper.rb:
  unmanaged: true
spec/acceptance/nodesets/centos-59-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/centos-64-x64-pe.yml:
  unmanaged: true
spec/acceptance/nodesets/centos-65-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/ubuntu-server-10044-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/ubuntu-server-12042-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/ubuntu-server-1404-x64.yml:
  unmanaged: true
